config/routes.rb
Rails.application.routes.draw do
  resources :appliances
  resources :panels
  root                'static_pages#home' # Controller#Action <!--get 'static_pages/home'-->
  get    'help'    => 'static_pages#help' #'static_pages/help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'geolocation'=>'static_pages#geolocation'
  get    'geolocationTesting'=>'static_pages#geolocationTesting'
  get    'index' =>'static_pages#index'
  get    'analysis' =>'static_pages#analysis'
  get    'howitworks' =>'static_pages#howitworks'
  
  get    'caniuse' =>'caniuse#index'
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  
  resources :optional_admin
  
  get 'admin_tools'             =>'admin_power#list'
  get 'admin_tools/user'        =>'admin_power#edit'
  get 'admin_tools/makeAdmin'   =>'admin_power#makeAdmin'
  get 'admin_tools/delAdmin'    =>'admin_power#delAdmin'
  get 'admin_tools/cleanup'     =>'admin_power#cleanup'

end

app/models/panel.rb
class Panel < ActiveRecord::Base
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  before_action :set_panel, only: [:show, :edit, :update, :destroy]

  # GET /panels
  # GET /panels.json
  def index
    @panels = Panel.all
  end

  # GET /panels/1
  # GET /panels/1.json
  def show
  end

  # GET /panels/new
  def new
    @panel = Panel.new
  end

  # GET /panels/1/edit
  def edit
  end

  # POST /panels
  # POST /panels.json
  def create
    @panel = Panel.new(panel_params)

    respond_to do |format|
      if @panel.save
        format.html { redirect_to @panel, notice: 'Panel was successfully created.' }
        format.json { render :show, status: :created, location: @panel }
      else
        format.html { render :new }
        format.json { render json: @panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panels/1
  # PATCH/PUT /panels/1.json
  def update
    respond_to do |format|
      if @panel.update(panel_params)
        format.html { redirect_to @panel, notice: 'Panel was successfully updated.' }
        format.json { render :show, status: :ok, location: @panel }
      else
        format.html { render :edit }
        format.json { render json: @panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panels/1
  # DELETE /panels/1.json
  def destroy
    @panel.destroy
    respond_to do |format|
      format.html { redirect_to panels_url, notice: 'Panel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_params
      params.require(:panel).permit(:name, :power, :tracking)
    end
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/views/panels/_form.html.erb
<%= form_for(@panel) do |f| %>
  <% if @panel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panel.errors.count, "error") %> prohibited this panel from being saved:</h2>

      <ul>
      <% @panel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="TextInputs" class="PanelsPage">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :power %><br>
      <%= f.text_field :power %>
    </div>
    <div class="field float_left">
      <%= f.label :tracking %><br>
      <%= f.check_box :tracking %>
    </div>
    <div class="actions" >
      <%= f.submit :class => "btn btn-info btn-lg" %>
    </div>
  </div>
<% end %>

app/views/panels/edit.html.erb
<% provide(:title, "Edit Panel") %>
<body class="background-solar-panel">
  <div class="PanelsPage">
    <h1>Editing Panel</h1>
    <%= render 'form' %>
    <div class="center">
        <%= link_to 'Show', @panel %> |
        <%= link_to 'Back', panels_path %>
    </div>
  </div>
</body>

app/views/panels/index.html.erb
<% provide(:title, "Panels") %>
<style>
  h1 {
    color: #000000;
  }
</style>
<body class="background-solar-panel">
  <div class="PanelsPage">
    <h1>Listing Panels</h1>
    
    <table class="panelchart">
      <thead>
        <tr>
          <th class="TableHeads">Name</th>
          <th class="TableHeads">Power(W)</th>
          <th class="TableHeads">Tracking</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @panels.each do |panel| %>
          <tr>
            <td class="NamePower"><%= link_to panel.name, panel %></td>
            <td class="NamePower"><%= panel.power %></td>
            <td class="NamePower"><%= panel.tracking %></td>
            <td class="NamePower"><%= link_to '', edit_panel_path(panel), class: "fa fa-pencil" %></td>
            <td class="NamePower"><%= link_to '', panel, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    </br>
    
    
    <div class="center">
      <a class="btn btn-info btn-lg" href="panels/new">
        New Panel
      </a>
    </div>
  </div>
</body>

app/views/panels/new.html.erb
<% provide(:title, "New Panel") %>
<body class="background-solar-panel">
  <div class="PanelsPage">
    <h1>New Panel</h1>
    
    <%= render 'form' %>
    
    <div class="center">
        <%= link_to 'Back', panels_path %>
    </div>
  </div>
</body>

app/views/panels/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<% provide(:title, "Showing Panel") %>
<style>
  h1 {
    color: #000000;
  }
</style>

<body class="background-solar-panel">
  <div class="PanelsPage" class="AppliancePaddingFix">
    <p>
      <h1>
        <strong><%= @panel.name %></strong>
      </h1>
    </p>
    
    <p class="NamePower">
      <strong>Rated Watts:</strong> W
      <%= @panel.power %>
    </p>
    
    <p class="NamePower">
      <strong>Tracking:</strong>
      <%= @panel.tracking %>
    </p>
    
    <div class="center">
      <%= link_to 'Edit', edit_panel_path(@panel) %> |
      <%= link_to 'Back', panels_path %>
    </div>
  </div>
</body>