config/routes.rb
Rails.application.routes.draw do
  resources :appliances
  resources :panels
  root                'static_pages#home' # Controller#Action <!--get 'static_pages/home'-->
  get    'help'    => 'static_pages#help' #'static_pages/help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'geolocation'=>'static_pages#geolocation'
  get    'geolocationTesting'=>'static_pages#geolocationTesting'
  get    'index' =>'static_pages#index'
  get    'analysis' =>'static_pages#analysis'
  get    'howitworks' =>'static_pages#howitworks'
  
  get    'caniuse' =>'caniuse#index'
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post    'login'  => 'sessions#create'
  delete  'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  
  resources :optional_admin
  
  get 'admin_tools'             =>'admin_power#list'
  get 'admin_tools/user'        =>'admin_power#edit'
  get 'admin_tools/makeAdmin'   =>'admin_power#makeAdmin'
  get 'admin_tools/delAdmin'    =>'admin_power#delAdmin'
  get 'admin_tools/cleanup'     =>'admin_power#cleanup'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size
  
  private
  
    # Validates the size of uploaded picture
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Picture must be less than 5 MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: [:destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created"
      redirect_to root_url
    else
      flash[:warning] = "Microposts can't be blank"
      redirect_to root_url
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  
  private
  
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<% micropost.id %>">
  <%#= link_to gravatar_for(micropost.user, size: 50), user_path(micropost.user) %>
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost_path(micropost), method: :delete, # or just micropost instead of the path
                                              data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>